worker:
  replicas:
    default: 1
    horizontalpodautoscaler:
      default:
        host_ip: 10.0.200.46
        port: 15692
        metrics_path: /metrics/per-object
        interval: 30s
        metric_name: rabbitmq_queue_messages_ready
        label_name: '{{ .Values.worker.chainId }}_indexation_etl_verify_all'
        replicas_maximum: 10
        threshold: 20
  limitsCpu: 0.1
  limitsMemory: 2000Mi
  requestsCpu: 0.1
  requestsMemory: 500Mi
  command: '[ "ethereumetl", "amqp_stream" ]'
  ## Following wars are rendered using tpl separately in template into Envs
  providerURL: '{{ .Values.worker.fullProviderURL }}'
  output: '{{ .Values.worker.chainDB }}'
  lag: '{{ .Values.worker.blocksToFinal }}'
  entityTypes: '{{ .Values.worker.verifyEntityTypes }}'
  ##
  env:
    ROUTING_KEY: 'block'
    POLLING_PERIOD: '60'
    BATCH_SIZE: '5'
    SERVICE_NAME: 'raw-verify-data-streamer'
    IS_VERIFIER: 'True'
    EXCHANGE_NAME: 'verifier_etl'
    QUEUE_NAME: 'verify_all'
    REWRITE_CLICKHOUSE: ''
    MAX_WORKERS: '20'
    BLOCK_BATCH_SIZE: '10'
    MIN_INSERT_BATCH_SIZE: '1'
