worker:
  replicas:
    default: 1
    horizontalpodautoscaler:
      default:
        host_ip: 10.0.200.46
        port: 15692
        metrics_path: /metrics/per-object
        interval: 30s
        metric_name: rabbitmq_queue_messages_ready
        label_name: '{{ .Values.worker.chainId }}_indexation_etl_token_balance'
        replicas_maximum: 10
        threshold: 20
  limitsCpu: 0.3
  limitsMemory: 1024Mi
  requestsCpu: 0.1
  requestsMemory: 500Mi
  command: '[ "ethereumetl", "amqp_stream" ]'
  ## Following wars are rendered using tpl separately in template into Envs
  providerURL: '{{ .Values.worker.fullProviderURL }}'
  output: '{{ .Values.worker.chainDB }}'
  lag: '0'
  entityTypes: 'token_balance'
  ##
  env:
    ENTITY_TYPES: 'token_balance'
    ROUTING_KEY: 'token_transfer'
    POLLING_PERIOD: '2'
    BATCH_SIZE: '5'
    SERVICE_NAME: 'raw-data-streamer-balance'
    REWRITE_CLICKHOUSE: ''
    MAX_WORKERS: '20'
    BLOCK_BATCH_SIZE: '100'
    MIN_INSERT_BATCH_SIZE: '1'
