version: '3.7'

services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    image: dexguru-indexer
    env_file:
      - .env
    restart: on-failure
    links:
      - clickhouse
      - rabbit
      - elasticsearch
    depends_on:
      - clickhouse
    command: >
      bash -c "CLICKHOUSE_URL=$OUTPUT alembic upgrade head
      && ethereumetl stream"
    volumes:
        - .:/app
        - clickhouse_data:/var/lib/clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:23.5.4.25
    ports:
      - "8123:8123" # HTTP interface
      - "9000:9000" # Native client interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped


  init-ch-db:
    image: yandex/clickhouse-client
    command: -h clickhouse -u default -q 'CREATE DATABASE IF NOT EXISTS ethereum'
    depends_on:
      - clickhouse
    links:
      - clickhouse

  rabbit:
    # Optional
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_VHOST: dex
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure

  elasticsearch:
    # Optional
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
    ports:
      - "9200:9200"


volumes:
  clickhouse_data:
