[tool.black]
line-length = 99
target-version = ["py310"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 99
known_first_party = ["blockchainetl", "ethereumetl", "schemas", "tests"]

[tool.ruff]
line-length = 150
ignore = [
    "C90",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D107",
    "D200",
    "D203",
    "D205",
    "D212",
    "D401",
    "D415",
    "E741",
    "Q000",
    "UP032",
    "UP038",
]
extend-select = ["Q", "RUF100", "UP", "I", "PERF", "D"]
isort = { known-first-party = ["blockchainetl", "ethereumetl", "schemas", "tests"] }
target-version = "py310"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
allow_untyped_calls = true
allow_untyped_defs = true
check_untyped_defs = true
strict_equality = true
warn_no_return = false
warn_redundant_casts = true
warn_return_any = false
warn_unreachable = true
warn_unused_ignores = true
namespace_packages = true
