---
image: 'registry.gitlab.com/telekomconsalting/dexguru/indexation-etl'
imageTag: ''
registrySecretName: registry-gitlab
appName: ''
pipeline: ''
kubeNamespace: ''

optimize-tables:
  command: '[ "ethereumetl", "optimize_tables" ]'
  env:
    SERVICE_NAME: "optimize-tables-job"
    PYTHONPATH: "."
  metadata:
    creationTimestamp: null
  restartPolicy: Never
  limitsCpu: 1.5
  limitsMemory: "15000Mi"
  requestsCpu: 0.2
  requestsMemory: "400Mi"
  concurrencyPolicy: Forbid


