class EntityType:
    BLOCK = 'block'
    TRANSACTION = 'transaction'
    RECEIPT = 'receipt'
    LOG = 'log'
    TOKEN_TRANSFER = 'token_transfer'
    TRACE = 'trace'
    GETH_TRACE = 'geth_trace'
    CONTRACT = 'contract'
    TOKEN = 'token'
    INTERNAL_TRANSFER = 'internal_transfer'

    ALL_FOR_STREAMING = [BLOCK, TRANSACTION, LOG, TOKEN_TRANSFER, TOKEN, GETH_TRACE, INTERNAL_TRANSFER]
    ALL_FOR_INFURA = [BLOCK, TRANSACTION, LOG, TOKEN_TRANSFER]
    ALL = [BLOCK, TRANSACTION, RECEIPT, LOG, TOKEN_TRANSFER, TRACE, CONTRACT, TOKEN, GETH_TRACE, INTERNAL_TRANSFER]
