---
image: docker-registry.dexguru.biz/dex.guru/indexation-etl/indexation-etl
imageTag: ''
registrySecretName: registry-harbor

raw-data-streamer:
  replicas:
    default: 1
  limitsCpu: 4
  limitsMemory: 9000Mi
  requestsCpu: 1
  requestsMemory: 1000Mi
  strategyType: 'Recreate'
  command: '[ "ethereumetl", "stream" ]'
  env:
    LAST_SYNCED_BLOCK_PROVIDER: 'clickhouse://testuser3:testplpassword@10.0.200.205:8123/dex_etl?table_name=last_synced_block'
    LAG: '0'
    OUTPUT: 'clickhouse://testuser3:testplpassword@10.0.200.205:8123/dex_etl,http://10.0.200.184:9200'
    ENTITY_TYPES: 'block,transaction,log,token_transfer,token_balance,error,token,token_transfer_priced'
    EXPORT_FROM_CLICKHOUSE: 'clickhouse://testuser3:testplpassword@10.0.200.205:8123/dex_etl'
    POLLING_PERIOD: '2'
    BATCH_SIZE: '5'
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"
    LOG_HANDLERS: '["console","logstash"]'
    SERVICE_NAME: 'raw-data-streamer'
    MAX_WORKERS: '10'
    ELASTIC_URL: 'http://10.0.200.184:9200'
  chainEnv:
    START_BLOCK:
      default: '1'
      optimism-10: '105287791'
      gnosis-100: '28341135'
      arbitrum-42161: '98842875'
      nova-42170: '10923456'
      fantom-250: '63741723'
      canto-7700: '4566159'
      eth-1: '17431241'
      acanto-7701: '1860704'
      avalanche-43114: '34619186'
      basetestnet-84531: '5490413'
    PROVIDER_URL:
      default: 'http://rpc-gw-stage.dexguru.biz/full/1'
      polygon-137: 'http://rpc-gw-stage.dexguru.biz/full/137'
      bsc-56: 'http://rpc-gw-stage.dexguru.biz/full/56'
      eth-1: 'http://rpc-gw-stage.dexguru.biz/full/1'
      canto-7700: 'http://rpc-gw-stage.dexguru.biz/full/7700'
      acanto-7701: 'http://canto-testnet.plexnode.wtf'
      fantom-250: 'http://rpc-gw-stage.dexguru.biz/full/250'
      optimism-10: 'http://rpc-gw-stage.dexguru.biz/full/10'
      gnosis-100: 'http://rpc-gw-stage.dexguru.biz/full/100'
      arbitrum-42161: 'http://rpc-gw-stage.dexguru.biz/full/42161'
      nova-42170: 'http://rpc-gw-stage.dexguru.biz/full/42170'
      basetestnet-84531: 'http://rpc-gw-stage.dexguru.biz/full/84531'
      base-8453: 'http://rpc-gw-stage.dexguru.biz/full/8453'
      avalanche-43114: 'http://10.0.100.136:9650/ext/bc/C/rpc'
    BLOCK_BATCH_SIZE:
      default: '1000'
      polygon-137: '1000'
      bsc-56: '1000'
      eth-1: '1000'
      canto-7700: '100'
      fantom-250: '100'
      optimism-10: '100'
      gnosis-100: '100'
      arbitrum-42161: '100'
      nova-42170: '100'
      acanto-7701: '100'
    SKIP_NONE_RECEIPTS:
      default: 'False'
      polygon-137: 'True'
    MIN_INSERT_BATCH_SIZE:
      default: '1'
      canto-7700: '1'
      fantom-250: '1'
      optimism-10: '1'
      gnosis-100: '1'
      arbitrum-42161: '1'
      nova-42170: '1'
      acanto-7701: '1'

raw-data-streamer-resync:
  replicas:
    default: 1
  limitsCpu: 4
  limitsMemory: 9000Mi
  requestsCpu: 1
  requestsMemory: 1000Mi
  strategyType: 'Recreate'
  command: '[ "ethereumetl", "stream" ]'
  env:
    LAST_SYNCED_BLOCK_PROVIDER: 'clickhouse://testuser3:testplpassword@10.0.200.205:8123/dex_etl?table_name=resync_blocks'
    LAG: '0'
    OUTPUT: 'clickhouse://testuser3:testplpassword@10.0.200.205:8123/dex_etl'
    POLLING_PERIOD: '2'
    BATCH_SIZE: '10'
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"
    LOG_HANDLERS: '["console","logstash"]'
    SERVICE_NAME: 'raw-resync-data-streamer'
    EXPORT_FROM_CLICKHOUSE: 'http://testuser3:testplpassword@10.0.200.180:8123/dex_etl'
    REWRITE_CLICKHOUSE: 'block,transaction,receipt,log,token_transfer,trace,geth_trace,contract,token,internal_transfer,token_balance,error'
  chainEnv:
    ENTITY_TYPES:
      default: 'block,transaction,log,token_transfer,internal_transfer,geth_trace'
      fantom-250: 'block,transaction,log,token_transfer'
      acanto-7701: 'block,transaction,log,token_transfer'
      gnosis-100: 'block,transaction,log,token_transfer'
      optimism-10: 'block,transaction,log,token_transfer'
    START_BLOCK:
      default: '1'
      optimism-10: '101280306'
      gnosis-100: '28116446'
      arbitrum-42161: '94531505'
      nova-42170: '9672550'
      fantom-250: '63088042'
      canto-7700: '4388552'
      eth-1: '17335059'
      acanto-7701: '1644828'
      basetestnet-84531: '4922000'
    END_BLOCK:
      default: null
      optimism-10: '105287791'
      gnosis-100: '28341135'
      arbitrum-42161: '98842875'
      nova-42170: '10923456'
      fantom-250: '63741723'
      canto-7700: '4566159'
      eth-1: '17431241'
      acanto-7701: '1860704'
      basetestnet-84531: '5490413'
    PROVIDER_URL:
      default: 'http://rpc-gw-prod.dexguru.biz/archive/1'
      polygon-137: 'http://rpc-gw-prod.dexguru.biz/archive/137'
      bsc-56: 'http://rpc-gw-prod.dexguru.biz/archive/56'
      eth-1: 'http://rpc-gw-prod.dexguru.biz/archive/1'
      canto-7700: 'http://rpc-gw-prod.dexguru.biz/archive/7700'
      acanto-7701: 'http://canto-testnet.plexnode.wtf'
      fantom-250: 'http://rpc-gw-prod.dexguru.biz/archive/250'
      optimism-10: 'http://rpc-gw-prod.dexguru.biz/archive/10'
      gnosis-100: 'http://rpc-gw-prod.dexguru.biz/archive/100'
      arbitrum-42161: 'http://rpc-gw-prod.dexguru.biz/archive/42161'
      nova-42170: 'http://rpc-gw-prod.dexguru.biz/archive/42170'
      basetestnet-84531: 'http://rpc-gw-prod.dexguru.biz/archive/84531'
      base-8453: 'http://rpc-gw-stage.dexguru.biz/archive/8453'
      avalanche-43114: 'http://10.0.100.136:9650/ext/bc/C/rpc'
    BLOCK_BATCH_SIZE:
      default: '1000'
    MAX_WORKERS:
      default: '5'
      polygon-137: '10'
      eth-1: '5'
      bsc-56: '12'
      canto-7700: '5'
      fantom-250: '5'
      optimism-10: '5'
      gnosis-100: '5'
      arbitrum-42161: '5'
      nova-42170: '5'
      acanto-7701: '5'
    SKIP_NONE_RECEIPTS:
      default: 'False'
      polygon-137: 'True'
    MIN_INSERT_BATCH_SIZE:
      default: '1000'

raw-traces-data-streamer:
  replicas:
    default: 1
  limitsCpu: 4
  limitsMemory: 9000Mi
  requestsCpu: 1
  requestsMemory: 1000Mi
  strategyType: 'Recreate'
  command: '[ "ethereumetl", "stream" ]'
  env:
    LAST_SYNCED_BLOCK_PROVIDER: 'clickhouse://testuser3:testplpassword@10.0.200.205:8123/dex_etl?table_name=last_synced_block_traces'
    OUTPUT: 'clickhouse://testuser3:testplpassword@10.0.200.205:8123/dex_etl,http://10.0.200.184:9200'
    POLLING_PERIOD: '2'
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"
    LOG_HANDLERS: '["console","logstash"]'
    SERVICE_NAME: 'raw-traces-data-streamer'
    EXPORT_FROM_CLICKHOUSE: 'http://testuser3:testplpassword@10.0.200.205:8123/dex_etl'
    REWRITE_CLICKHOUSE: ''
    ELASTIC_URL: 'http://10.0.200.184:9200'
  chainEnv:
    ENTITY_TYPES:
      default: 'block,geth_trace,internal_transfer,native_balance,token,contract,internal_transfer_priced'
    PROVIDER_URL:
      default: 'http://rpc-gw-stage.dexguru.biz/full/1'
      polygon-137: 'http://rpc-gw-stage.dexguru.biz/full/137'
      bsc-56: 'http://rpc-gw-stage.dexguru.biz/full/56'
      eth-1: 'http://rpc-gw-stage.dexguru.biz/full/1'
      canto-7700: 'http://rpc-gw-stage.dexguru.biz/full/7700'
      acanto-7701: 'http://canto-testnet.plexnode.wtf'
      fantom-250: 'http://rpc-gw-stage.dexguru.biz/debug/250'
      optimism-10: 'http://rpc-gw-stage.dexguru.biz/full/10'
      gnosis-100: 'http://rpc-gw-stage.dexguru.biz/full/100'
      arbitrum-42161: 'http://rpc-gw-stage.dexguru.biz/full/42161'
      nova-42170: 'http://rpc-gw-stage.dexguru.biz/full/42170'
      basetestnet-84531: 'http://rpc-gw-stage.dexguru.biz/full/84531'
      base-8453: 'http://rpc-gw-stage.dexguru.biz/full/8453'
      avalanche-43114: 'http://10.0.100.136:9650/ext/bc/C/rpc'
    BLOCK_BATCH_SIZE:
      default: '1000'
      fantom-250: '10'
    MAX_WORKERS:
      default: '10'
      fantom-250: '5'
    BATCH_SIZE:
      default: '5'
    SKIP_NONE_RECEIPTS:
      default: 'False'
      polygon-137: 'True'
    MIN_INSERT_BATCH_SIZE:
      default: '1'
    LAG:
      default: 1
      arbitrum-42161: 40
      fantom-250: 10

raw-verify-data-streamer:
  replicas:
    default: 1
  limitsCpu: 4
  limitsMemory: 9000Mi
  requestsCpu: 1
  requestsMemory: 1000Mi
  strategyType: 'Recreate'
  command: '[ "ethereumetl", "stream" ]'
  env:
    LAST_SYNCED_BLOCK_PROVIDER: 'clickhouse://testuser3:testplpassword@10.0.200.205:8123/dex_etl?table_name=last_synced_block_verify'
    OUTPUT: 'clickhouse://testuser3:testplpassword@10.0.200.205:8123/dex_etl'
    POLLING_PERIOD: '30'
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"
    LOG_HANDLERS: '["console","logstash"]'
    SERVICE_NAME: 'raw-verify-data-streamer'
    EXPORT_FROM_CLICKHOUSE: 'http://testuser3:testplpassword@10.0.200.205:8123/dex_etl'
    REWRITE_CLICKHOUSE: 'block,transaction,log,token_transfer,token_balance,geth_trace,internal_transfer'
    IS_VERIFIER: 'True'
  chainEnv:
    LAG:
      default: 100
      eth-1: 64
      bsc-56: 64
      polygon-137: 200
      arbitrum-42161: 200
      nova-42170: 200
      optimism-10: 200
    ENTITY_TYPES:
      default: 'block,transaction,log,token_transfer,internal_transfer,geth_trace'
      acanto-7701: 'block,transaction,log,token_transfer'
      gnosis-100: 'block,transaction,log,token_transfer'
    PROVIDER_URL:
      default: 'http://rpc-gw-stage.dexguru.biz/full/1'
      polygon-137: 'http://rpc-gw-stage.dexguru.biz/full/137'
      bsc-56: 'http://rpc-gw-stage.dexguru.biz/full/56'
      eth-1: 'http://rpc-gw-stage.dexguru.biz/full/1'
      canto-7700: 'http://rpc-gw-stage.dexguru.biz/full/7700'
      acanto-7701: 'http://canto-testnet.plexnode.wtf'
      fantom-250: 'http://rpc-gw-stage.dexguru.biz/debug/250'
      optimism-10: 'http://rpc-gw-stage.dexguru.biz/full/10'
      gnosis-100: 'http://rpc-gw-stage.dexguru.biz/full/100'
      arbitrum-42161: 'http://rpc-gw-stage.dexguru.biz/full/42161'
      nova-42170: 'http://rpc-gw-stage.dexguru.biz/full/42170'
      basetestnet-84531: 'http://rpc-gw-stage.dexguru.biz/full/84531'
      base-8453: 'http://rpc-gw-stage.dexguru.biz/full/8453'
      avalanche-43114: 'http://10.0.100.136:9650/ext/bc/C/rpc'
    BLOCK_BATCH_SIZE:
      default: '100'
    MAX_WORKERS:
      default: '10'
    BATCH_SIZE:
      default: '5'
    SKIP_NONE_RECEIPTS:
      default: 'False'
      polygon-137: 'True'
    MIN_INSERT_BATCH_SIZE:
      default: '1'
