worker:
  replicas:
    default: 1
    polygon-137: 2
    bsc-56: 2
    arbitrum-42161: 2
  limitsCpu: 0.7
  limitsMemory: 9000Mi
  requestsCpu: 0.1
  requestsMemory: 1000Mi
  command: '[ "ethereumetl", "amqp_stream" ]'
  ## Following wars are rendered using tpl separately in template into Envs
  providerURL: '{{ .Values.worker.fullProviderURL }}'
  output: '{{ .Values.worker.chainDB }}'
  lag: '0'
  entityTypes: 'token_balance'
  ##
  env:
    ENTITY_TYPES: 'token_balance'
    ROUTING_KEY: 'token_transfer'
    POLLING_PERIOD: '2'
    BATCH_SIZE: '5'
    SERVICE_NAME: 'raw-data-streamer-balance'
    REWRITE_CLICKHOUSE: ''
    MAX_WORKERS: '20'
    BLOCK_BATCH_SIZE: '100'
    MIN_INSERT_BATCH_SIZE: '1'
