---
image: 'registry.gitlab.com/telekomconsalting/dexguru/indexation-etl'
imageTag: ''
registrySecretName: registry-gitlab

raw-data-streamer:
  replicas:
    default: 1
  limitsCpu: 4
  limitsMemory: 9000Mi
  requestsCpu: 1
  requestsMemory: 1000Mi
  strategyType: 'Recreate'
  command: '[ "ethereumetl", "stream" ]'
  env:
    LAST_SYNCED_BLOCK_PROVIDER: 'clickhouse+native://testuser3:testplpassword@10.0.200.180/dex_etl?table_name=last_synced_block'
    LAG: '0'
    OUTPUT: 'clickhouse://testuser3:testplpassword@10.0.200.180/dex_etl'
    START_BLOCK: '1'
    ENTITY_TYPES: 'block,transaction,log,token_transfer'
    POLLING_PERIOD: '2'
    BATCH_SIZE: '10'
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"
    LOG_HANDLERS: '["console","logstash"]'
    SERVICE_NAME: 'raw-data-streamer'

  chainEnv:
    BLOCK_BATCH_SIZE:
      default: '1000'
      polygon-137: '150'
      bsc-56: '1000'
      eth-1: '200'
      canto-7700: '100'
      fantom-250: '100'
      optimism-10: '100'
      gnosis-100: '100'
      arbitrum-42161: '100'
      nova-42170: '100'
    MAX_WORKERS:
      default: '5'
      polygon-137: '10'
      eth-1: '5'
      bsc-56: '12'
      canto-7700: '5'
      fantom-250: '5'
      optimism-10: '5'
      gnosis-100: '5'
      arbitrum-42161: '5'
      nova-42170: '5'
    SKIP_NONE_RECEIPTS:
      default: 'False'
      polygon-137: 'True'
    MIN_INSERT_BATCH_SIZE:
      default: '1000'
      canto-7700: '1'
      fantom-250: '1'
      optimism-10: '1'
      gnosis-100: '1'
      arbitrum-42161: '1'
      nova-42170: '1'
