---
image: 'registry.gitlab.com/telekomconsalting/dexguru/indexation-etl'
imageTag: ''
registrySecretName: registry-gitlab
appName: ''
pipeline: ''
kubeNamespace: ''

optimize-tables:
  command: '[ "ethereumetl", "optimize_tables" ]'
  env:
    SERVICE_NAME: "optimize-tables-job"
    OUTPUT: "clickhouse://testuser3:testplpassword@ch-prod-indexation-01.dexguru.biz/dex_etl"
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"
    LOG_HANDLERS: '["console","logstash"]'
    PYTHONPATH: "."
  metadata:
    creationTimestamp: null
  restartPolicy: Never
  limitsCpu: 1.5
  limitsMemory: "15000Mi"
  requestsCpu: 0.2
  requestsMemory: "400Mi"
  concurrencyPolicy: Forbid

data-consistency-check:
  restartPolicy: Never
  limitsCpu: 1.5
  limitsMemory: "15000Mi"
  requestsCpu: 0.2
  requestsMemory: "400Mi"
  concurrencyPolicy: Forbid
  command: '[ "ethereumetl", "check_data_consistency" ]'
  env:
    LAG: '0'
    OUTPUT: 'clickhouse://testuser3:testplpassword@ch-prod-indexation-01.dexguru.biz/dex_etl'
    ENTITY_TYPES: 'block,transaction,log,token_transfer'
    POLLING_PERIOD: '2'
    BATCH_SIZE: '10'
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"
    LAST_SYNCED_BLOCK_PROVIDER: 'clickhouse+native://testuser3:testplpassword@ch-prod-indexation-01.dexguru.biz/dex_etl?table_name=data_consistency'
    LOG_HANDLERS: '["console","logstash"]'
    SERVICE_NAME: 'data-consistency-check'
    EXPORT_FROM_CLICKHOUSE: 'http://testuser3:testplpassword@ch-prod-indexation-01.dexguru.biz/dex_etl'
  chainEnv:
    START_BLOCK:
      default: '1'
    PROVIDER_URL:
      default: 'http://rpc-gw-prod.dexguru.biz/archive/1'
      polygon-137: 'http://rpc-gw-prod.dexguru.biz/archive/137'
      bsc-56: 'http://rpc-gw-prod.dexguru.biz/archive/56'
      eth-1: 'http://rpc-gw-prod.dexguru.biz/archive/1'
      canto-7700: 'http://rpc-gw-prod.dexguru.biz/archive/7700'
      acanto-7701: 'http://canto-testnet.plexnode.wtf'
      fantom-250: 'http://rpc-gw-prod.dexguru.biz/archive/250'
      optimism-10: 'http://rpc-gw-prod.dexguru.biz/archive/10'
      gnosis-100: 'http://rpc-gw-prod.dexguru.biz/archive/100'
      arbitrum-42161: 'http://rpc-gw-prod.dexguru.biz/archive/42161'
      nova-42170: 'http://rpc-gw-prod.dexguru.biz/archive/42170'
      base-84531: 'http://rpc-gw-prod.dexguru.biz/archive/84531'
    BLOCK_BATCH_SIZE:
      default: '1000'
    MAX_WORKERS:
      default: '5'
      polygon-137: '10'
      eth-1: '5'
      bsc-56: '12'
      canto-7700: '5'
      fantom-250: '5'
      optimism-10: '5'
      gnosis-100: '5'
      arbitrum-42161: '5'
      nova-42170: '5'
      acanto-7701: '5'
    SKIP_NONE_RECEIPTS:
      default: 'False'
      polygon-137: 'True'
    MIN_INSERT_BATCH_SIZE:
      default: '1'


raw-traces-data-resync:
  replicas:
    default: 1
    base-8453: 0
  limitsCpu: 4
  limitsMemory: 9000Mi
  requestsCpu: 1
  requestsMemory: 1000Mi
  restartPolicy: Never
  concurrencyPolicy: Forbid
  command: '[ "ethereumetl", "stream" ]'
  env:
    LAST_SYNCED_BLOCK_PROVIDER: 'clickhouse+native://testuser3:testplpassword@ch-prod-indexation-01.dexguru.biz/dex_etl?table_name=last_synced_block_traces_resync'
    OUTPUT: 'clickhouse+native://testuser3:testplpassword@ch-prod-indexation-01.dexguru.biz/dex_etl'
    POLLING_PERIOD: '2'
    LOGSTASH: "logstash-logstash.logging.svc.cluster.local"
    LOG_HANDLERS: '["console","logstash"]'
    SERVICE_NAME: 'raw-traces-data-streamer-resync'
    EXPORT_FROM_CLICKHOUSE: 'http://testuser3:testplpassword@ch-prod-indexation-01.dexguru.biz/dex_etl'
    REWRITE_CLICKHOUSE: ''
    START_BLOCK: '1'
  chainEnv:
    ENTITY_TYPES:
      default: 'block,geth_trace,internal_transfer'
    PROVIDER_URL:
      default: 'http://rpc-gw-stage.dexguru.biz/archive/1'
      polygon-137: 'http://rpc-gw-stage.dexguru.biz/archive/137'
      bsc-56: 'http://rpc-gw-stage.dexguru.biz/archive/56'
      eth-1: 'http://rpc-gw-stage.dexguru.biz/archive/1'
      canto-7700: 'http://rpc-gw-stage.dexguru.biz/archive/7700'
      acanto-7701: 'http://canto-testnet.plexnode.wtf'
      fantom-250: 'http://rpc-gw-stage.dexguru.biz/debug/250'
      optimism-10: 'http://rpc-gw-stage.dexguru.biz/archive-orig/10'
      gnosis-100: 'http://rpc-gw-stage.dexguru.biz/archive/100'
      arbitrum-42161: 'http://rpc-gw-stage.dexguru.biz/archive/42161'
      nova-42170: 'http://rpc-gw-stage.dexguru.biz/archive/42170'
      basetestnet-84531: 'http://rpc-gw-stage.dexguru.biz/archive/84531'
      base-8453: 'http://rpc-gw-stage.dexguru.biz/full/8453'
    BLOCK_BATCH_SIZE:
      default: '1000'
      optimism-10: '100'
    MAX_WORKERS:
      default: '10'
    BATCH_SIZE:
      default: '5'
    SKIP_NONE_RECEIPTS:
      default: 'False'
      polygon-137: 'True'
    MIN_INSERT_BATCH_SIZE:
      default: '50000'
    END_BLOCK:
      default: '17770319'
      polygon-137: '45502792'
      bsc-56: '30272663'
      eth-1: '17770319'
      canto-7700: '5240814'
      fantom-250: '66285832'
      optimism-10: '107346470'
      arbitrum-42161: '114809254'
      nova-42170: '15637085'
      acanto-7701: '1860704'
      basetestnet-84531: '7549150'